Final Project/application/amazon_clone/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

Final Project/application/website/urls.py
"""
Created by Joseph Edradan
Github: https://github.com/josephedradan

Date: 5/18/2020

Purpose:

Details:

Description:

Notes:

IMPORTANT NOTES:

Explanation:

Reference:

"""

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
"""
IMPORTANT NOTE: YOU MUST USE website: IN HTML FILES SUCH AS IN AN <a> tag like href="{% url 'website:home'%}"
because we have app_name
"""
app_name = 'website'

# Not using generic views
# urlpatterns = [
#     # ex: /polls/
#     path('', views.index, name='index'),
#     # TAKE ANY ARBITRARY NUMBER FROM THE URL AND RUN the views.detail FUNCTION WITH TEH URL ARGUMENT AS A PARAMETER
#     # ex: /polls/5/
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

# Using generic views
urlpatterns = [
    # path('', views.HomeView.as_view(), name='index'),
    path('', views.PageHome.as_view(), name='home'),  # The default page will be from home since the default in the main urls is ''
    # ex: /polls/5/
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),  # Generic view
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),  # Generic view
    # path('<int:question_id>/vote/', views.vote, name='vote'),  # Non Generic view

    # path('product/', views.invalid_url, name='product'),
    path('product/<int:site_product_id>/', views.PageProduct.as_view(), name='product'),
    path('register', views.page_register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),  # No template will result in the admin logout page
    path('profile/', views.PageProfile.as_view(), name='profile'),
    # path('removeFromOrder/<int:customer_order_id>/<int:seller_product_listing_id>/',views.site_remove_from_order, name='remove_from_order'),
    # path('deleteOrder/<int:customer_order_id>/', views.site_delete_order, name='delete_order'),
    # path('createOrder/', views.site_create_order, name='create_customer_order'),
    # path('deleteSellerProductListing/<int:seller_product_listing_id>/',views.site_delete_seller_product_listing, name='delete_seller_product_listing'),
    path('createSellerProductListing/', views.PageCreateSellerProductListing.as_view(), name='create_seller_product_listing')
]

Final Project/application/website/forms.py
"""
Created by Joseph Edradan
Github: https://github.com/josephedradan

Date: 5/19/2020

Purpose:

Details:

Description:

Notes:

IMPORTANT NOTES:

Explanation:

Reference:

"""
from django import forms
from django.contrib.auth.models import User as User_auth  # Used for the actual User the proper way
from django.contrib.auth.forms import UserCreationForm

from .models import User, SiteProductComment, Product, SellerProductListing, SiteProduct, Manufacturer


class UserRegisterFormExtended(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=45)  # Field name made lowercase.
    last_name = forms.CharField(max_length=45)  # Field name made lowercase.

    class Meta:
        model = User_auth
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]


"""
Reference:
    https://www.youtube.com/watch?v=Tja4I_rgspI

"""


class UserRegisterFromCustom(forms.ModelForm):
    # username = forms.CharField(max_length=45)  # Field name made lowercase.
    # password = forms.CharField(max_length=45)  # Field name made lowercase.
    address_1 = forms.CharField(max_length=255)  # Field name made lowercase.
    address_2 = forms.CharField(max_length=255, required=False, )  # Field name made lowercase.
    city = forms.CharField(max_length=255)  # Field name made lowercase.
    state_province = forms.CharField(max_length=255)  # Field name made lowercase.
    zip = forms.CharField(max_length=5, required=False, )  # Field name made lowercase.
    phone_1 = forms.CharField(max_length=45)  # Field name made lowercase.
    phone_2 = forms.CharField(max_length=45, required=False, )  # Field name made lowercase.

    # email = forms.CharField(max_length=255)  # Field name made lowercase.

    class Meta:
        model = User
        fields = (
            # 'username', # Sub it with something
            # 'password', # Sub it with something
            'address_1',
            'address_2',
            'city',
            'state_province',
            'zip',
            'phone_1',
            'phone_2',
            # 'email', # Needs to be added
        )


"""
Reference:
    https://www.youtube.com/watch?v=zgF-KtQPqxQ
"""


class FormOrder(forms.Form):
    pass


class FormComment(forms.Form):
    comment = forms.CharField(widget=forms.Textarea, required=False)
    # images = forms.ImageField(required=False)

    # Choice Range: https://stackoverflow.com/questions/8859504/django-form-dropdown-list-of-numbers
    product_rating = forms.ChoiceField(required=False, choices=[(x, x) for x in range(1, 6)], initial=3)

    class Meta:
        model = SiteProductComment
        fields = (
            'comment',
            'product_rating',
        )


class CreateProduct(forms.Form):
    id = forms.ChoiceField(label="Manufacturer ID",
                           choices=[(x, x) for x in Manufacturer.objects.all().values_list('id', flat=True)])
    product_name = forms.CharField()

    # THIS IS HERE BECAUSE I CANT GET THE RESULT OF THE FIELD DIRECTLY FROM A forms.ModelForm OBJECT
    site_product_id = forms.ChoiceField(label="Site product ID", choices=[(x, x) for x in
                                                                          SiteProduct.objects.all().values_list(
                                                                              'site_product_id', flat=True)])

    class Meta:
        model = Product
        fields = (
            'id',
            'product_name',
        )


class CreateSellerProductListing(forms.ModelForm):
    # id = forms.IntegerField()  # Seller ID
    # product object

    product_pricing = forms.DecimalField()
    product_description = forms.CharField()

    class Meta:
        model = SellerProductListing
        fields = (
            'product_pricing',
            'product_description',
        )

Final Project/application/website/views.py
from django.contrib import messages
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.db import connection
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import generic, View

from .models import (User,
                     SiteProduct,
                     SiteProductComment,
                     SellerProductListing,
                     Customer,
                     Seller,
                     Manufacturer,
                     AuthUser)

from .forms import *

"""


Reference:
    How to log a user in¶
    https://docs.djangoproject.com/en/3.0/topics/auth/default/
    
    Django - How to use decorator in class-based view methods?
    https://stackoverflow.com/questions/31633259/django-how-to-use-decorator-in-class-based-view-methods
    
    Django form with two submit buttons . . . one requires fields and one doesn't 
    (multiple forms)
    https://stackoverflow.com/questions/35666570/django-form-with-two-submit-buttons-one-requires-fields-and-one-doesnt
    
    Setting the selected value on a Django forms.ChoiceField 
    (initial value for a field)
    https://stackoverflow.com/questions/657607/setting-the-selected-value-on-a-django-forms-choicefield
    
    Call Django on HTML button click
    (Button and method='GET' in HTML for calling a view) 
    https://stackoverflow.com/questions/48438575/call-django-on-html-button-click/48438962
    
    Field value not turning up in request.POST querydict - python django
    (HTML Form format)
    https://stackoverflow.com/questions/32297532/field-value-not-turning-up-in-request-post-querydict-python-django
"""


# TODO: WE GET ERROR IF WE DELETE IF IT'S IN A SHIPPING INFORMATION

def _console_printer(text):
    spacing = 100
    print(spacing * "*")

    if isinstance(text, (list, tuple)):
        for i in text:
            if isinstance(i, dict):
                for key, value in i.items():
                    print(key)
                    if isinstance(value, (list, tuple)):
                        [print('\t', z) for z in value]
            else:
                print(i)
    else:
        print(text)
    print(spacing * "*")


#
# class HomeView(generic.ListView):
#     # model = Question
#     template_name = 'home/home.html'


def invalid_url(request):
    # raise Http404("Invalid URL")
    return redirect('website:home')
    # return redirect('home/home.html') # Does not work as intended


class PageHome(View):
    def get(self, request, *args, **kwargs):
        """
        TODO:
        // SITE PRODUCTS

        :param request:
        :return:

        :param request:
        :param args:
        :param kwargs:
        :return:
        """

        # Get the tags for a site_product
        list_site_product_ids = SiteProduct.objects.raw(
            """
            SELECT Site_product_ID FROM site_product;
            """
        )

        list_dict_seller_product_listing_remaining = []

        for i in list_site_product_ids:
            # Calling procedure get_seller_product_listing_remaining in MySQL
            with connection.cursor() as cursor:
                cursor.callproc('cis_363_project.get_seller_product_listing_remaining', [i.site_product_id])
                seller_product_listing_remaining = cursor.fetchall()

                list_dict_seller_product_listing_remaining.append({i.site_product_id: seller_product_listing_remaining})

        # print(list_dict_seller_product_listing_remaining)

        seller_product_listing_remaining_header = (
            'Seller Product Listing ID', 'Seller ID', 'Seller Name', 'Seller Rating', 'Manufacturer Name',
            'Product Name', 'Product ID', 'Product Pricing', 'Product Description')

        context = {
            'list_dict_seller_product_listing_remaining': list_dict_seller_product_listing_remaining,
            'seller_product_listing_remaining_header': seller_product_listing_remaining_header
        }

        return render(request, 'home/home.html', context)
        # return HttpResponse("HELLO TEST")

    def post(self):
        pass


@method_decorator(login_required, name='dispatch')
class PageCreateSellerProductListing(View):

    # @method_decorator(login_required())
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            form_product = CreateProduct()
            form_seller_product_listing = CreateSellerProductListing()

            context = {'form_product': form_product,
                       'form_seller_product_listing': form_seller_product_listing,
                       }

            return render(request, 'product/create_and_list_new_product.html', context)

    # @method_decorator(login_required())
    def post(self, request, *args, **kwargs):
        """
        SELLERS ONLY
          TODO: CREATE A SITE PRODUCT, ASSIGN THE PRODUCT ID TO IT

        :param request:
        :return:
        """

        if request.user.is_authenticated:

            user_current = request.user

            # Calling procedure is_seller in MySQL
            with connection.cursor() as cursor:
                cursor.callproc('cis_363_project.is_seller', [user_current.id])
                is_seller = cursor.fetchone()

            # print("-"*100)
            # print(is_seller)

            if is_seller[0] == 1:

                if request.method == 'POST':
                    form_product = CreateProduct(request.POST)
                    form_seller_product_listing = CreateSellerProductListing(request.POST)

                    if form_product.is_valid() and form_seller_product_listing.is_valid():
                        print("-" * 100)
                        print("form_product", form_product)
                        print("form_product", type(form_product))
                        print("form_product.id", type(form_product.cleaned_data.get('id')))

                        # FORM IS NOT A MODEL FORM BECAUSE OF THE MANUFACTURER ID
                        form_product_id = form_product.cleaned_data.get('id')
                        form_product_product_name = form_product.cleaned_data.get('product_name')
                        form_product_site_product_id = form_product.cleaned_data.get('site_product_id')

                        manufacturer_object = Manufacturer.objects.get(pk=form_product_id)

                        temp_product = Product.objects.create(
                            id=manufacturer_object,
                            product_name=form_product_product_name
                        )

                        temp_product.save()

                        seller_product_listing = form_seller_product_listing.save(commit=False)

                        seller_product_listing.id = Seller.objects.get(pk=user_current.id)

                        seller_product_listing.product = temp_product

                        seller_product_listing.site_product_id = form_product_site_product_id

                        seller_product_listing.save()

                        messages.success(request,
                                         f'You have created a new Seller product listing ID: {seller_product_listing.seller_product_listing_id} in site_product_id: {seller_product_listing.site_product_id}')

                        return redirect('website:profile')
                    else:
                        return redirect("website:home")


@method_decorator(login_required, name='dispatch')
class PageProfile(View):
    """
    TODO: PRIME, PRIME PAYMENT, SHOPPING CART, ORDERS, CREDIT CARD

    """

    def get(self, request, *args, **kwargs):
        user_current = request.user
        if request.user.is_authenticated:
            # Calling procedure is_seller in MySQL
            with connection.cursor() as cursor:
                cursor.callproc('cis_363_project.is_seller', [user_current.id])
                is_seller = cursor.fetchone()

            if is_seller[0] == 1:
                return self.get_seller(request, user_current, *args, **kwargs)
            else:
                return self.get_customer(request, user_current, *args, **kwargs)
        else:
            return invalid_url(request)

    def get_customer(self, request, user_current, *args, **kwargs):
        # Calling procedure is_prime in MySQL
        with connection.cursor() as cursor:
            cursor.callproc('cis_363_project.is_prime', [user_current.id])
            prime_member = cursor.fetchone()

        # Calling procedure get_user_all_orders in MySQL
        with connection.cursor() as cursor:
            cursor.callproc('cis_363_project.get_user_orders_all', [user_current.id])
            user_all_orders = cursor.fetchall()

        list_dict_user_orders_all = []

        for order_id, customer_order_id, sum_total in user_all_orders:
            # Calling procedure get_items_in_customer_order_id in MySQL
            with connection.cursor() as cursor:
                cursor.callproc('cis_363_project.get_items_in_customer_order_id', [order_id])
                order = cursor.fetchall()

                list_dict_user_orders_all.append({order_id: order})

        context = {
            'is_customer': True,
            'user_all_orders': user_all_orders,
            'user_all_orders_headers': ("Order ID", "Amount of items in order", "Order Total"),
            'list_dict_user_orders_all': list_dict_user_orders_all,
            'list_user_orders_all_headers': ("Seller product listing ID", "Name", "Price", "Description",
                                             "Seller", "Manufacturer"),
            'prime_member': True if prime_member else False,

Final Project/application/website/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'website:register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

Final Project/application/website/templates/users/logout.html
{% extends "base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'website:login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

Final Project/application/website/templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <!--        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">-->
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
                <p>
                    {% if is_customer %}
                        Prime Member: {{ prime_member }}<br/>
                    {% endif %}
                    Address 1: {{ user_profile.address_1 }}<br/>
                    Address 2: {{ user_profile.address_2 }}<br/>
                    City: {{ user_profile.city }}<br/>
                    State/Province: {{ user_profile.state_province }}<br/>
                    Zip: {{ user_profile.zip }}<br/>
                    Phone 1: {{ user_profile.phone_1 }}<br/>
                    Phone 2: {{ user_profile.phone_2 }}<br/>
                </p>

                {% if is_customer %}
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary btn-sm" name="customer_create_order">Create new
                            Order
                        </button>
                    </form>
                {% else %}
                    <h2>Revenue: {{ seller_revenue.0 }}</h2>
                    <a href="{% url 'website:create_seller_product_listing' %}">
                        <button type="button" class="btn btn-primary btn-sm">List new Product</button>
                    </a>
                {% endif %}

                {% if is_customer %}
                    <h2 class="div_padding_custom">Your orders</h2>
                    <table>
                        <tr>
                            {% for header in user_all_orders_headers %}
                                <td>{{ header }}</td>
                            {% endfor %}
                        </tr>
                        {% for row in user_all_orders %}
                            <tr>
                                {% for item in row %}
                                    <td>{{ item }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                    <h2 class="div_padding_custom">Individual Orders</h2>
                    {% for dict_user_orders in list_dict_user_orders_all %}
                        {% for order_id, order in dict_user_orders.items %}
                            <div class="div_padding_custom">
                                <h3 style="float:left; margin-right: 5px; line-height: 1;">Order ID: {{ order_id }}</h3>
                                <form method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="customer_order_id" value="{{ order_id }}">
                                    <button type="submit" class="btn btn-danger" name="customer_delete_order"
                                            value="placeholder">Delete Order
                                    </button>
                                </form>
                            </div>
                            <table>
                                <tr>
                                    {% for header in list_user_orders_all_headers %}
                                        <td>{{ header }}</td>
                                    {% endfor %}
                                </tr>
                                {% for row in order %}
                                    <tr>
                                        {% for item in row %}
                                            <td>{{ item }}</td>
                                        {% endfor %}
                                        <td style="border:0; background-color: #ffffff;">
                                            <form method="post">
                                                {% csrf_token %}
                                                <input type="hidden" name="customer_order_id" value="{{ order_id }}">
                                                <input type="hidden" name="seller_product_listing_id"
                                                       value="{{ row.0 }}">
                                                <button type="submit" class="btn btn-danger"
                                                        name="customer_remove_item_from_order" value="placeholder">
                                                    Remove
                                                </button>
                                            </form>

                                        </td>
                                    </tr>
                                {% endfor %}

                            </table>
                        {% endfor %}
                    {% endfor %}
                {% else %}
                    <h2 class="div_padding_custom">Your items Not Sold</h2>
                    {% for dict_seller_product_listing_not_sold in list_dict_seller_product_listing_not_sold %}
                        {% for site_product_id, seller_product_listing_not_sold in dict_seller_product_listing_not_sold.items %}
                            <div class="div_padding_custom">
                                <h3 style=" margin-right: 5px; line-height: 1;">
                                    site_product_id: {{ site_product_id }}</h3>
                            </div>
                            <table>
                                <tr>
                                    {% for header in seller_product_listing_not_sold_headers %}
                                        <td>{{ header }}</td>
                                    {% endfor %}
                                </tr>
                                {% for row in seller_product_listing_not_sold %}
                                    <tr>
                                        {% for item in row %}
                                            <td>{{ item }}</td>
                                        {% endfor %}
                                        <td style="border:0; background-color: #ffffff;">
                                            <form method="post">
                                                {% csrf_token %}
                                                <input type="hidden" name="site_product_id" value="{{ row.0 }}">
                                                <button type="submit" class="btn btn-danger"
                                                        name="seller_delete_product_listing"
                                                        value="placeholder">Remove
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}

                            </table>
                        {% endfor %}
                    {% endfor %}
                    <h2 class="div_padding_custom">Your Items Sold</h2>
                    {% for dict_seller_product_listing_sold in list_dict_seller_product_listing_sold %}
                        {% for site_product_id, seller_product_listing_sold in dict_seller_product_listing_sold.items %}
                            <div class="div_padding_custom">
                                <h3 class="dict_list">site_product_id: {{ site_product_id }}</h3>

                            </div>
                            <table>
                                <tr>
                                    {% for header in seller_product_listing_sold_headers %}
                                        <td>{{ header }}</td>
                                    {% endfor %}
                                </tr>
                                {% for row in seller_product_listing_sold %}
                                    <tr>
                                        {% for item in row %}
                                            <td>{{ item }}</td>
                                        {% endfor %}
                                    </tr>
                                {% endfor %}
                            </table>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <!-- FORM HERE -->
    </div>
{% endblock content %}

Final Project/application/website/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Account</legend>
                {{ form_default|crispy }}
                {{ form_user_profile|crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'website:login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}